pipeline{
    agent any
    stages{
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Build Image') {
            steps {
                script {
                    docker build --tag siceiapp-master .
                    docker run --detach siceiapp-master
                }
            }
        }
        
    }
}