pipeline{
    agent any
    stages{
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Build Image') {
            steps {
                docker build --tag siceiapp-master .
            }
        }
        
    }
}