pipeline{
    agent any
    stages{
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Build Image') {
            steps {
                script {
                    docker build -t siceiapp-master .
                    docker run -it siceiapp-master cmd
                }
            }
        }
        
    }
}